sudo: required
language: cpp
services: docker
notifications:
  email:
    on_success: change
    on_failure: always
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang
before_install:
  # install cmake and gtest
  - sudo apt-get install cmake libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
  # install root
  - wget https://root.cern.ch/download/root_v6.06.08.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
  - tar xvzf root_v6.06.08.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
  - source root/bin/thisroot.sh
install:
  # create dedicated build folder
  - cd .. && mkdir build && cd build
  - cmake ../GenFit
  - make VERBOSE=1
  - make tests
script:
  # generate test geometry
  - cd bin
  - root -l -b -q ../../GenFit/test/makeGeom.C
  # run unit tests
  - ./gtests
  - ./unitTests

